spring:
  application:
    name: hhrpc-demo-consumer

server:
  port: 8080

hhrpc:
  providers: http://localhost:8081,http://localhost:8082
  zkservers: localhost:2181
  zkroot: hhrpc

app:
  id: hhrpc
  namespace: public
  env: dev
  retries: 2

logging:
  level:
    root: error
    com.hhrpc.hhrpc: debug